config/routes.rb
Rails.application.routes.draw do
  # Set the root to the main dashboard
  root 'dashboard#index'
  
  # Make sure admin goes to the admin dashbaord
  get '/admin' => 'admin/dashboard#index'

  
  # Main dashboard only has index for now.
  resources :dashboard, only: [:index]
  resources :addresses, only: [:create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resource :user, only: [:new, :create, :edit, :update, :destroy]
  resource :cart
  resource :orders, only: [:update, :destroy]
  resource :checkouts, only: [:update]
  resource :credit_cards, only: [:destroy]

  namespace :admin do
    # Admin dashboard, only using index for now.
    resources :dashboard, only: [:index]
  	resources :categories
  	resources :products
  	resources :users
  	resources :addresses
    resources :orders
  	resources :credit_cards, only: [:destroy]
    resources :order_contents, only: [:update, :destroy, :create]
  end
end

app/views/admin/_left_navbar.html.erb
<navbar class="col-sm-2 grey-border">
	<p class="text-center"><b>Navigation Options</b></p>

	<ul class="navbar-main text-center">
		<li><%= link_to "Users", admin_users_path %></li>
		<li><%= link_to "Addresses", admin_addresses_path %></li>
		<li><%= link_to "Orders", admin_orders_path %></li>
		<li><%= link_to "Products", admin_products_path %></li>
		<li><%= link_to "Categories", admin_categories_path %></li>
	</ul>

	<ul class="under-navbar text-center">
		<li><%= link_to "Analytics Dashboard", "#" %></li>
	</ul>
	
</navbar>

app/views/admin/_main_title.html.erb
<header class="row">
	<div class="col-sm-12">
		<h1 class="text-center">Viking Store Admin Portal</h1>
	</div>
</header>

app/views/admin/index.html.erb
<h2>Admin Homepage</h2>
<p>please select a resource from the sidebar!</p>