config/routes.rb
Rails.application.routes.draw do
  # Set the root to the main dashboard
  root 'dashboard#index'
  
  # Make sure admin goes to the admin dashbaord
  get '/admin' => 'admin/dashboard#index'

  
  # Main dashboard only has index for now.
  resources :dashboard, only: [:index]
  resources :addresses, only: [:create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resource :user, only: [:new, :create, :edit, :update, :destroy]
  resource :cart
  resource :orders, only: [:update, :destroy]
  resource :checkouts, only: [:update]
  resource :credit_cards, only: [:destroy]

  namespace :admin do
    # Admin dashboard, only using index for now.
    resources :dashboard, only: [:index]
  	resources :categories
  	resources :products
  	resources :users
  	resources :addresses
    resources :orders
  	resources :credit_cards, only: [:destroy]
    resources :order_contents, only: [:update, :destroy, :create]
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	belongs_to :product
	has_one :credit_card, through: :user
	has_many :categories, through: :products
	has_many :products, through: :order_contents
	has_many :order_contents, class_name: "OrderContents"
	accepts_nested_attributes_for :order_contents, 
																	:reject_if => :all_blank, 
                                	:allow_destroy => :true

  accepts_nested_attributes_for :credit_card, 
																	:reject_if => :all_blank, 
                                	:allow_destroy => :true

	validates :shipping_id, :billing_id, :presence => true

	after_update :remove_nil_quantities

	# Return the total number of orders since a particular time.
	# See the view for how to utilize the yield here.
	def self.total_submitted_orders

		if block_given?
			in_timeframe = yield
			in_timeframe.where("checkout_date NOT null").count
		else
			Order.where("checkout_date NOT null").count
		end

	end

	# Returns the total revenue since a particular timeframe.
	# See the view for how to utilize the yield here.
	def self.total_revenue

		if block_given?
			in_timeframe = yield
			in_timeframe.select("SUM(price * quantity) AS total_revenue").
			joins("JOIN products ON order_contents.product_id = products.id JOIN order_contents ON orders.id = order_contents.order_id").
			where("checkout_date IS NOT null").first.total_revenue
		else
			select("SUM(price * quantity) AS total_revenue").
			joins("JOIN products ON order_contents.product_id = products.id JOIN order_contents ON orders.id = order_contents.order_id").
			where("checkout_date IS NOT null").first.total_revenue
		end

	end

	# Returns the name and total order value of the highest order for a 
	# particular time period. This timeframe is given as a block when the 
	# method is called, for now it will be an ActiveRecord::Relation which will
	# then have further queries called on it. Further down I found a better way to 
	# go about this but this method also works.
 	def self.highest_order_value

		if block_given?
			in_timeframe = yield
			in_timeframe.select("users.first_name AS first_name, users.last_name AS last_name, SUM(products.price * order_contents.quantity) AS order_price").
			joins("JOIN users ON users.id = orders.user_id JOIN order_contents ON orders.id = order_contents.order_id JOIN products ON order_contents.product_id = products.id").
			where("orders.checkout_date IS NOT null").
			group("order_contents.order_id").
			order("order_price DESC").
			limit(1).first
		else
			select("users.first_name AS first_name, users.last_name AS last_name, SUM(products.price * order_contents.quantity) AS order_price").
			joins("JOIN users ON users.id = orders.user_id JOIN order_contents ON orders.id = order_contents.order_id JOIN products ON order_contents.product_id = products.id").
			where("orders.checkout_date IS NOT null").
			group("order_contents.order_id").
			order("order_price DESC").
			limit(1).first
		end

	end

	# Returns the first+last name and total order value for the user 
	# with the highest lifetime order value.
	def self.highest_lifetime_value

		select("users.first_name AS first_name, users.last_name AS last_name, SUM(products.price * order_contents.quantity) AS total_price").
		joins("JOIN users ON users.id = orders.user_id JOIN order_contents ON orders.id = order_contents.order_id JOIN products ON order_contents.product_id = products.id").
		where("orders.checkout_date IS NOT null").
		group("users.id").
		order("total_price DESC").
		limit(1).first

	end

	# Returns the first+last name as well as the average order value for the 
	# user with the highest average order value.
	def self.highest_average_value

		select("users.first_name AS first_name, users.last_name AS last_name, AVG(products.price * order_contents.quantity) AS average_value").
		joins("JOIN users ON users.id = orders.user_id JOIN order_contents ON orders.id = order_contents.order_id JOIN products ON order_contents.product_id = products.id").
		where("orders.checkout_date IS NOT null").
		group("users.id").
		order("average_value DESC").
		limit(1).first

	end

	# Returns the first+last name, as well as the number of orders, 
	# for the user who has placed the most orders ever.
	def self.most_orders_placed

		select("users.first_name AS first_name, users.last_name AS last_name, COUNT(order_contents.order_id) AS orders").
		joins("JOIN users ON users.id = orders.user_id JOIN order_contents ON orders.id = order_contents.order_id JOIN products ON order_contents.product_id = products.id").
		where("orders.checkout_date IS NOT null").
		group("users.id").
		order("orders DESC").
		limit(1).first

	end

	# Average value of all orders w/ timeframe support. NOTE: After
	# messing around with the .yield way of doing timeframes I think that
	# a simple parameter is probably the easiest way to actually go about this.
	# Yield can lead to other problems (for instance, in this situation)
	# when there are aggregate functions and other .where's to be concerned with.
	### TODO: Go back and make all class functions which currently use yield
	### take a timeframe (or similar) parameter.
	def self.average_order_value(timeframe = nil)

			if timeframe.nil?
				average_stats = select("SUM(products.price * order_contents.quantity) AS order_value, COUNT(DISTINCT order_contents.order_id) AS number_of_orders").
				joins("JOIN users ON users.id = orders.user_id JOIN order_contents ON orders.id = order_contents.order_id JOIN products ON order_contents.product_id = products.id").
				where("orders.checkout_date IS NOT null").limit(1).first
				average_stats.order_value / average_stats.number_of_orders
			else
				average_stats = select("SUM(products.price * order_contents.quantity) AS order_value, COUNT(DISTINCT order_contents.order_id) AS number_of_orders").
				joins("JOIN users ON users.id = orders.user_id JOIN order_contents ON orders.id = order_contents.order_id JOIN products ON order_contents.product_id = products.id").
				where("orders.checkout_date IS NOT null").where("orders.checkout_date >= ?", timeframe).limit(1).first
				average_stats.order_value / average_stats.number_of_orders
			end

	end

	# This will take a date parameter and return the number of orders 
	# and the value of those orders on a particular day.
	def self.order_by_day(date)
		select("COUNT(DISTINCT orders.id) AS order_quantity, SUM(order_contents.quantity * products.price) AS order_value").
		joins("JOIN order_contents ON orders.id = order_contents.order_id JOIN products ON order_contents.product_id = products.id").
		where("orders.checkout_date IS NOT null").
		where("orders.checkout_date BETWEEN ? AND ?", date.beginning_of_day, date.end_of_day).
		limit(1).first
	end

	# Returns the quantity of orders and the value of those orders for a given timeframe.
	# Technically it doesn't have to be a week but I am using it as such.
	def self.order_by_week(start_date, end_date)
		select("COUNT(DISTINCT orders.id) AS order_quantity, SUM(order_contents.quantity * products.price) AS order_value").
		joins("JOIN order_contents ON orders.id = order_contents.order_id JOIN products ON order_contents.product_id = products.id").
		where("orders.checkout_date IS NOT null").
		where("orders.checkout_date BETWEEN ? AND ?", start_date.beginning_of_day, end_date.end_of_day).
		limit(1).first
	end

	def order_total
		products.sum("price * quantity")
	end

private
	# Runs through the list of order_contents for this order and 
	# destroys any with quantity == 0
	def remove_nil_quantities
		self.order_contents.each do |order_content|
			if order_content.quantity <= 0
				order_content.destroy!
			end
		end
	end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController

	def index
		save_referer_to_session
		if check_search_user
			@valid_search_user = true
			@orders = User.find(params[:search_user_id]).orders
		else
			@valid_search_user = false
			@orders = Order.all.limit(100)
		end
	end

	def show
		save_referer_to_session
		@order = Order.find(params[:id])
		@shipping_address = Address.find(@order.shipping_id)
		@billing_address = Address.find(@order.billing_id)
		@credit_card = CreditCard.where("user_id = #{@order.user_id}").first
		@order_items = OrderContents.where("order_id = #{@order.id}")
	end

	def new
		save_referer_to_session
		@order = Order.new
		@user = User.find(params[:user_id])
		@credit_card = CreditCard.where("user_id = ?", params[:user_id])
	end

	def create
		@order = Order.new(whitelisted_order_params)
		if @order.save 
			flash[:success] = "Order added successfully!"
			redirect_to edit_admin_order_path(@order.id)
		else
			render :new
		end
	end

	def edit
		save_referer_to_session
		@order = Order.find(params[:id])
		@user = @order.user
		@order_contents = OrderContents.where("order_id = ?", params[:id])
		@new_order_content = OrderContents.new
	end

	def update
		@order = Order.find(params[:id])
		if @order.checkout_date.nil? && params[:order][:order_status] == "placed"
			@order.checkout_date = Time.now
		end
		if @order.update(whitelisted_order_params)
			flash[:success] = "Order updated successfully!"
			redirect_to admin_orders_path(:search_user_id => params[:order][:id])
		else
			render :new
		end
	end

	def destroy
		@order = Order.find(params[:id])
		if @order.destroy
			flash[:success] = "Order deleted successfully!"
			redirect_to admin_orders_path(:search_user_id => params[:order][:user_id])
		else
			redirect_to session.delete(:return_to)
		end
	end

private 

	def whitelisted_order_params
		params.require(:order).permit(:shipping_id, :billing_id, :user_id, :checkout_date)
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def update
		current_user
		@cart_order = find_cart(@current_user)
		if @cart_order.update(whitelisted_order_params)
			flash[:success] = "Order updated successfully"
			redirect_to edit_cart_path
		else
			flash[:error] = "User could not be updated"
			render :edit
		end
	end

	def destroy
		current_user
		cart = find_cart(@current_user)
		if cart.destroy
			flash[:success] = "Cart deleted successfully."
			create_new_cart(@current_user)
			redirect_to dashboard_index_path
		else
			flash[:error] = "Error deleting cart."
			render :show
		end
	end


	def whitelisted_order_params
		params.require(:order).
			permit( :id,
							:shipping_id,
							:billing_id,
	            :order_contents_attributes => [
	           		:quantity, 
	           		:id, 
	           		:_destroy
	           ]
			)
	end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper

	# Get total value for a particular order_id
	def total_order_value(order_id)
		Order.select("SUM(price * quantity) AS total_revenue").
		where("order_id = #{order_id}").
		joins("JOIN products ON order_contents.product_id = products.id JOIN order_contents ON orders.id = order_contents.order_id").
		first.total_revenue
	end

	def order_item_quantity(order_id)
		Order.select("SUM(quantity) AS total_quantity").
		where("order_id = ?", order_id).
		joins("JOIN products ON order_contents.product_id = products.id JOIN order_contents ON orders.id = order_contents.order_id").
		first.total_quantity
	end

	def is_order_placed?(order)
		order_status = []

		order_status[0]=(order.checkout_date.present? ? "Placed" : "Unplaced")

		# This will be used to format our CSS
		order_status[1]=(order_status[0] == "Placed" ? "status-placed" : "status-unplaced")

		order_status
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_order_form.html.erb
<table class="table table-striped">

	<tbody>
		<!-- User ID -->
		<tr>
			<td>Customer ID:</td>
			<td><%= @user.id %></td>
		</tr>

		<!-- Link to Customer -->
		<tr>
			<td>Customer:</td>
			<td><%= link_to "#{@user.first_name} #{@user.last_name}", admin_user_path(@user.id) %></td>
		</tr>

		<!-- Date Placed -->
		<tr>
			<td>Date Placed:</td>
			<td><%= @order.checkout_date || "N/A" %></td>
		</tr>
	</tbody>
</table>

<div class="row">
	<div class="col-sm-12">
		<%= link_to "Edit Customer Profile", edit_admin_user_path(@user.id) %>

		<%= form_for [:admin, @order] do |f| %>
			
			<div class="form-group col-sm-12">
				<%= f.label :shipping_id, "Shipping Address" %>
				<%= f.collection_select(:shipping_id, Address.all, :id, :street_address, {selected: @user.shipping_id}, {class: "form-control"} ) %>
			</div>

			<div class="form-group col-sm-12">
				<%= f.label :billing_id, "Shipping Address" %>
				<%= f.collection_select(:billing_id, Address.all, :id, :street_address, {selected: @user.billing_id}, {class: "form-control"} ) %>
			</div>

			<div class="form-group col-sm-12">
				<%= label_tag :credit_card, "Credit Card" %>
				<%= select_tag :credit_card, options_from_collection_for_select(CreditCard.all, :id, :card_number, selected: @user.credit_card.id), class: "form-control" %>
			</div>

			<%= hidden_field_tag "order[user_id]", @user.id %>

			<%= f.submit :class => "btn btn-primary col-sm-2" %>

		<% end %>
	</div><!-- col-sm-12 -->
</div><!-- row -->

app/views/admin/orders/edit.html.erb
<h2>Edit Order for Order #<%= @order.id %>:</h2>

<%= render partial: "admin/shared/errors", :locals => { :error_object => @order } %>

<%= render partial: "order_form" %>

<h2>Order Status:</h2>

<%= form_tag([:admin, @order], method: :patch) do %>
	<%= label_tag 'order_status_placed', 'Placed:', class: 'status-placed' %>
	<%= radio_button_tag 'order[order_status]', 'placed', is_order_placed?(@order)[0] == "Placed" ? true : false %>
	<%= label_tag 'order_status_unplaced', 'Unplaced:', class: 'status-unplaced' %>
	<%= radio_button_tag 'order[order_status]', 'unplaced', is_order_placed?(@order)[0] == "Unplaced" ? true: false  %>
	<%= hidden_field_tag 'order[user_id]', @order.user.id %>
	<%= submit_tag "Update Order Information", class: 'btn btn-primary' %>
<% end %>

<h2>Edit Order Contents:</h2>

<table class="table table-striped">
	<thead class="all-bold">
		<tr>
			<td>ID</td>
			<td>Quantity</td>
			<td>Price</td>
			<td>Total Price</td>
			<td>Remove</td>
		</tr>
	</thead>

	<tbody>
		
		<% @order_contents.each do |order_content| %>
			<tr>
				<%= form_tag([:admin, order_content], method: :patch) do %>
					<td><%= order_content.id %></td>
				
				
					<td><%= text_field_tag("quantity", order_content.quantity) %></td>
							<%= hidden_field_tag("order_content_id", order_content.id) %>

					<td><%= number_to_currency(order_content.product.price) %></td>
					<td><%= number_to_currency(order_content.product.price * order_content.quantity) %></td>
					<td><%= link_to "Remove", admin_order_content_path(order_content.id), method: :delete %></td>
					<td><%= submit_tag "Change Quantity", class: "btn btn-info" %></td>
				<% end %>
			</tr>
		<% end %>

	</tbody>
</table>

<%= link_to "Delete Order", admin_order_path(@order.id), method: :delete, data: { confirm: "Are you sure?" } %>

<h2>Add Products to Order:</h2>

<table class="table table-striped">
	<thead class="all-bold">
		<tr>
			<td>Product ID</td>
			<td>Quantity</td>
			<td>Submit</td>
		</tr>
	</thead>
		
	<tbody>
		<%= form_tag "/admin/order_contents#create" do %>
					<%= hidden_field_tag("order_id", @order.id) %>
			<td><%= text_field_tag("product_id") %></td>
			<td><%= text_field_tag("quantity") %></td>
			<td><%= submit_tag "Add Product", class: "btn btn-info" %></td>
		<% end %>
	</tbody>

</table>

app/views/admin/orders/index.html.erb
<!-- Orders Index Page -->
<h2><%= generate_index_title(params[:search_user_id] ||= nil, @valid_search_user) %></h2>
<p><b>NOTE:</b> Orders can only be created from a user profile page!</p> 

<% if @valid_search_user %>
	<%= link_to "Create Order for User", new_admin_order_path(:user_id => params[:search_user_id]), class: "btn btn-primary action-button" %>
<% else %>
	<%= render partial: "admin/shared/user_filter_form", :locals => { :submit_path => admin_orders_path } %>
<% end %>

<table class="table table-striped">

	<thead class="all-bold">
		<tr>
			<td>ID</td>
			<td>User ID</td>
			<td>Address</td>
			<td>City</td>
			<td>State</td>
			<td>Quantity</td>
			<td>Total Value</td>
			<td>Status</td>
			<td>Date Placed</td>
			<td>Actions</td>
		</tr>
	</thead>
	
	<tbody>
		
		<% @orders.each do |order| %>
	
			<tr>
				<td><%= order.id %></td>
				<td><%= link_to order.user.id, admin_user_path(order.user) %></td>
				<td><%= Address.find(order.shipping_id).street_address %></td>
				<td><%= Address.find(order.shipping_id).city.name %></td>
				<td><%= Address.find(order.shipping_id).state.name %></td>
				<td><%= order_item_quantity(order.id) %></td>
				<td><%= number_to_currency(total_order_value(order.id)) %></td>
				<td><span class="<%= is_order_placed?(order)[1] %>"><%= is_order_placed?(order)[0] %></td>
				<td><%= order.checkout_date || "N/A" %></td>
				<td>
					<%= link_to "Show", admin_order_path(order) %> | 
					<%= link_to "Edit", edit_admin_order_path(order) %> | 
					<%= link_to "Delete", admin_order_path(order), :method => :delete, :data => {:confirm=>'Are you sure?'} %>
				</td>
			</tr>

		<% end %>

	</tbody>
</table>

app/views/admin/orders/new.html.erb
<h2>Create New Order for <%= "#{@user.first_name} #{@user.last_name}" %>:</h2>

<%= render partial: "admin/shared/errors", :locals => { :error_object => @order } %>

<%= render partial: "order_form" %>

<p class="col-sm-12 text-center">You can add products on the next screen,<br/> once order has been created.</p>

app/views/admin/orders/show.html.erb
<h2>Order #<%= @order.id %> <%= is_order_placed?(@order)[0] == "Unplaced" ? "Shopping Cart" : "Info" %>:</h2>
<table class="table table-striped">

	<tbody>
		<!-- User ID -->
		<tr>
			<td>Customer ID:</td>
			<td><%= @order.user_id %></td>
		</tr>

		<!-- Link to Customer -->
		<tr>
			<td>Customer:</td>
			<td><%= link_to "#{@order.user.first_name} #{@order.user.last_name}", admin_user_path(@order.user_id) %></td>
		</tr>

		<!-- Date Placed -->
		<tr>
			<td>Date Placed:</td>
			<td><%= @order.checkout_date || "N/A" %></td>
		</tr>
	</tbody>
</table>
<%= link_to "Edit Customer Profile", edit_admin_user_path(@order.user_id) %>


<!-- ORDER STATUS -->

<h2>Order Status:</h2>
<% order_status = is_order_placed?(@order) %>
<h3 class="<%= order_status[1] %>"><%= order_status[0] %></h3>

<!-- /ORDER STATUS -->

<!-- SHIPPING ADDRESS -->

<h2>Shipping Address:</h2>
<table class="table table-striped">

	<tbody>
		<!-- Street -->
		<tr>
			<td>Street:</td>
			<td><%= @shipping_address.street_address %></td>
		</tr>

		<!-- City -->
		<tr>
			<td>City:</td>
			<td><%= @shipping_address.city.name %></td>
		</tr>

		<!-- State -->
		<tr>
			<td>State:</td>
			<td><%= @shipping_address.state.name %></td>
		</tr>
	</tbody>
</table>

<!-- /SHIPPING ADDRESS -->

<!-- BILLING ADDRESS -->

<h2>Billing Address:</h2>
<table class="table table-striped">

	<tbody>
		<!-- Street -->
		<tr>
			<td>Street:</td>
			<td><%= @billing_address.street_address %></td>
		</tr>

		<!-- City -->
		<tr>
			<td>City:</td>
			<td><%= @billing_address.city.name %></td>
		</tr>

		<!-- State -->
		<tr>
			<td>State:</td>
			<td><%= @billing_address.state.name %></td>
		</tr>
	</tbody>
</table>

<!-- /BILLING ADDRESS -->

<!-- BILLING CARD -->

<h2>Billing Card:</h2>
<table class="table table-striped">

	<tbody>
		<!-- Last Four -->
		<tr>
			<td>Last Four:</td>
			<td><%= @credit_card.nil? ? "N/A" : @credit_card.card_number %></td>
		</tr>
	</tbody>
</table>

<!-- /BILLING CARD -->

<!-- ACTION LINKS -->

<div class="action-links">
	<%= link_to "Edit", edit_admin_order_path(@order) %> | 
	<%= link_to "Delete", admin_order_path, :method => :delete, :data => {:confirm=>'Are you sure?'} %>
</div>

<!-- /ACTION LINKS -->

<!-- ORDER CONTENTS -->

<h2>Order Contents:</h2>
<table class="table table-striped">

	<tbody>
		<thead class="all-bold">
			<tr>
				<td>Product ID</td>
				<td>Product</td>
				<td>Quantity</td>
				<td>Price</td>
				<td>Total Price</td>
			</tr>
		</thead>

		<tbody>
			<% @order_items.each do |order_item| %>
				<tr>
					<td><%= order_item.id %></td>
					<td><%= link_to order_item.product.name, admin_product_path(order_item.product.id) %></td>
					<td><%= order_item.quantity %></td>
					<td><%= number_to_currency(order_item.product.price) %></td>
					<td><%= number_to_currency((order_item.quantity) * (order_item.product.price)) %></td>
				</tr>
			<% end %>

		</tbody>
		
	</tbody>
</table>

<!-- /ORDER CONTENTS -->