config/routes.rb
Rails.application.routes.draw do
  # Set the root to the main dashboard
  root 'dashboard#index'
  
  # Make sure admin goes to the admin dashbaord
  get '/admin' => 'admin/dashboard#index'

  
  # Main dashboard only has index for now.
  resources :dashboard, only: [:index]
  resources :addresses, only: [:create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resource :user, only: [:new, :create, :edit, :update, :destroy]
  resource :cart
  resource :orders, only: [:update, :destroy]
  resource :checkouts, only: [:update]
  resource :credit_cards, only: [:destroy]

  namespace :admin do
    # Admin dashboard, only using index for now.
    resources :dashboard, only: [:index]
  	resources :categories
  	resources :products
  	resources :users
  	resources :addresses
    resources :orders
  	resources :credit_cards, only: [:destroy]
    resources :order_contents, only: [:update, :destroy, :create]
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_filter :require_address_ids_carts
	before_filter :current_user

	def edit
		@cart_order = find_cart(@current_user)
	end	

	def show
		@cart_order = find_cart(@current_user)
		@credit_card = (@cart_order.credit_card ? @cart_order.credit_card : CreditCard.new)
	end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/edit.html.erb
<header class="row">
	<div class="col-sm-12 text-center">
		<h2>Shopping Cart Contents</h2>
	</div>
</header>

<main class="row">
	
	<div class="col-sm-8 col-sm-offset-2">
			
		<%= form_for(@cart_order, as: :order, :url => orders_path) do |order_fields| %>

			<% @cart_order.order_contents.each do |item| %>

				<div class="row cart-block-wrapper">

					<div class="col-sm-8 cart-block-left">
						<div class="col-sm-12 pull-left cart-block-left-content">
							
							<div class="col-sm-8">
								<h3><%= item.product.name %></h3>
								<p class="category-name"><%= item.product.category.name %></p>	
							</div>
							
							<div class="col-sm-4">
								<p class="price"><%= number_to_currency(item.product.price) %> / each</p>
							</div>
						</div>
					</div>

					<div class="col-sm-4 cart-block-right">
						<div class="col-sm-12 pull-right cart-block-right-content">
							<table class="table no-border text-center">
								<thead>
									<tr>
										<td>Quantity</td>
										<td>Total Price</td>
									</tr>
								</thead>

								<tbody>
									<%= order_fields.fields_for :order_contents, item do |order_content_fields| %>
										<td>
											<%= order_content_fields.text_field :quantity, class: "form-control" %>
								      <%= order_content_fields.label :_destroy, "Remove item?" %>
								      <%= order_content_fields.check_box :_destroy %>
										</td>

									<% end %>
									<td><%= number_to_currency(item.product.price * item.quantity) %></td>									
								</tbody>
							</table>
							
						</div>
					</div>

				</div> <!-- /row cart-block-wrapper -->

			<% end %>
			
			<div class="row cart-block-wrapper">
				
				<div class="col-sm-8">
					<section class="col-sm-12 order-total text-center">
						<h3>Total</h3>
						<p><%= number_to_currency(@cart_order.order_total) %></p>
					</section>
				</div>

				<div class="col-sm-4">
					<section class="col-sm-12 order-submit-buttons ">
						<%= order_fields.submit class: "form-control btn btn-info" %>
						
						<% unless @cart_order.products.count == 0 %>
							<%= link_to "Check Out", cart_path, class: "form-control btn btn-primary" %>
						<% end %>
					</section>
				</div>

			</div><!-- /row -->

		<% end %> <!-- /form_for -->

	</div> <!-- div col-sm-8 wrapper w/ offset -->

</main> <!-- /main row -->

app/views/carts/show.html.erb
<header class="row">
	<div class="col-sm-12 text-center">
		<h2>Checkout</h2>
	</div>
</header>

<main class="row">
	
	<div class="col-sm-8 col-sm-offset-2">
		
		<%= form_for(@cart_order, as: :order, :url => checkouts_path) do |order_fields|  %>	

			<section class="block-left col-sm-6">
				
				<div class="block-content-wrapper col-sm-12">
					<h3>Shipping + Billing</h3>

					<!-- Shipping Address -->
					<div class="form-group col-sm-12">
						<span class="pull-left"><%= order_fields.label :shipping_id, "Shipping Address:" %></span>
  					<%= collection_select :default_ids, :shipping_id, @cart_order.user.addresses, :id, :street_address, {}, {class: "form-control"} %>
					</div>

					<!-- Billing Address -->	
					<div class="form-group col-sm-12">
						<span class="pull-left"><%= order_fields.label :billing_id, "Billing Address:" %></span>
  					<%= collection_select :default_ids, :billing_id, @cart_order.user.addresses, :id, :street_address, {}, {class: "form-control"} %>
					</div>

					<!-- Edit saved addresses goes to User edit page -->
					<div class="form-group col-sm-12">
						<span class="pull-left"><%= link_to "Edit Saved Addresses", edit_user_path %></span>
					</div>

					<!-- Credit Card Section -->
					<%= order_fields.fields_for :credit_card, @credit_card do |credit_card_fields| %>
						<div class="form-group col-sm-12">
							<span class="pull-left"><%= credit_card_fields.label :card_number  %></span>
	      			<%= credit_card_fields.text_field :card_number, class: "form-control" %>
						</div>

						<div class="form-group col-sm-6">
							<span class="pull-left"><%= credit_card_fields.label :exp_month  %></span>
	      			<%= credit_card_fields.text_field :exp_month, class: "form-control" %>
						</div>

						<div class="form-group col-sm-6">
							<span class="pull-left"><%= credit_card_fields.label :exp_year  %></span>
	      			<%= credit_card_fields.text_field :exp_year, class: "form-control" %>
						</div>
						
						<div class="form-group col-sm-12">
							<% if @current_user.credit_card %>
								<span class="pull-left"><%= link_to "Delete Card", credit_cards_path, :method => :delete, :data => {:confirm => "Are you sure?" } %></span>
							<% end %>
						</div>

					<% end %>
				</div>

			</section>

			<section class="block-right col-sm-6 ">
				
				<div class="block-content-wrapper col-sm-12">
					<h3>Review + Complete</h3>
					<table class="table table-striped">
						
						<thead>
							<tr>
								<td>Product</td>
								<td>Quantity</td>
								<td>Price</td>
								<td>Total</td>
							</tr>
						</thead>

						<tbody>
							<% @cart_order.order_contents.each do |order_content| %>	
								<tr>
									<td><%= order_content.product.name %></td>
									<td><%= order_content.quantity %></td>
									<td><%= order_content.product.price %></td>
									<td><%= number_to_currency(order_content.quantity * order_content.product.price) %></td>
								</tr>
							<% end %>
						</tbody>

					</table>

					<div class="col-sm-4 pull-left">
						<span class="pull-left"><%= link_to "Edit Order", edit_cart_path %></span><br>
						<span class="pull-left"><%= link_to "Delete Order", orders_path, :method => :delete, :data => {:confirm => "Are you sure?"} %></span>	
					</div>

					<div class="col-sm-8 pull-right">
						<h3>Total: <%= number_to_currency(@cart_order.order_total) %></h3>
					</div>

				</div>

				<div class="block-content-wrapper col-sm-12">
					<h3>Place Your Order</h3>
					<p><%= order_fields.submit "Place Order", class: "btn btn-primary form-control" %></p>
				</div>
	
			</section>

		<% end %> <!-- end form_for -->

	</div> <!-- div col-sm-8 wrapper w/ offset -->

</main> <!-- /main row -->