config/routes.rb
Rails.application.routes.draw do
  # Set the root to the main dashboard
  root 'dashboard#index'
  
  # Make sure admin goes to the admin dashbaord
  get '/admin' => 'admin/dashboard#index'

  
  # Main dashboard only has index for now.
  resources :dashboard, only: [:index]
  resources :addresses, only: [:create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resource :user, only: [:new, :create, :edit, :update, :destroy]
  resource :cart
  resource :orders, only: [:update, :destroy]
  resource :checkouts, only: [:update]
  resource :credit_cards, only: [:destroy]

  namespace :admin do
    # Admin dashboard, only using index for now.
    resources :dashboard, only: [:index]
  	resources :categories
  	resources :products
  	resources :users
  	resources :addresses
    resources :orders
  	resources :credit_cards, only: [:destroy]
    resources :order_contents, only: [:update, :destroy, :create]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :addresses, dependent: :destroy
	accepts_nested_attributes_for :addresses, 
                                :reject_if => :all_blank, 
                                :allow_destroy => :true
	has_many :cities
	has_many :states
	has_one :credit_card, dependent: :destroy
	has_many :orders
	has_many :products, through: :order_contents
	has_many :order_contents, through: :orders
	belongs_to :shipping_address, foreign_key: :shipping_id, class_name: "Address", dependent: :destroy  
	belongs_to :billing_address, foreign_key: :billing_id, class_name: "Address", dependent: :destroy  
	
	accepts_nested_attributes_for :credit_card, 
                                :allow_destroy => :true

	# Make sure that we delete the cart when a user is deleted but not
	# any orders that have been completed.
	after_destroy :cleanup_cart

	validates :first_name, :last_name, :email, :presence => true, length: {in: 1..64}
	#validates :credit_card, presence: { scope: :order }, :on => :update

	def self.total

		# Allow us to pass in a block which will get the rows in a 
		# particular timeframe.
		if block_given?
			in_timeframe = yield
			in_timeframe.count
		else
			User.count
		end
		
	end


	# Get the 3 states that have the highest 
	# number of clients based on our billing addresses.
	def self.top_states

		select("states.name AS name, COUNT(*) AS client_total ").
		joins("JOIN addresses ON users.billing_id = addresses.id JOIN states ON addresses.state_id = states.id").
		where("billing_id IS NOT null").
		group("states.name").
		order("client_total DESC").
		limit(3)

	end


	# Get the 3 cities that have the greatest 
	# number of clients based on our billing addresses.
	def self.top_cities

		select("cities.name AS name, COUNT(*) AS client_total ").
		joins("JOIN addresses ON users.billing_id = addresses.id JOIN cities ON addresses.city_id = cities.id").
		where("billing_id IS NOT null").
		group("cities.name").
		order("client_total DESC").
		limit(3)

	end

private
	def cleanup_cart
		Order.where("user_id = #{self.id}").destroy_all("checkout_date IS null")
	end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

	def index
		save_referer_to_session
		# We're saving the user ID here because if we click the delete CC info 
		# button on this page we need that information saved.
		save_user_to_session(params[:id])
		@users = User.all
	end

	def show
		save_referer_to_session
		save_user_to_session(params[:id])
		@user = User.find(params[:id])
		@user_addresses = @user.addresses
		@user_credit_card = CreditCard.where("user_id = #{params[:id]}").first
		@orders = @user.orders
	end

	def new
		save_referer_to_session
		@user = User.new
	end

	def create
		@user = User.new(whitelisted_user_params)
		if @user.save 
			flash[:success] = "User created successfully!"
			redirect_to admin_user_path(@user.id)
		else
			render :new
		end
	end

	def edit
		save_referer_to_session
		save_user_to_session(params[:id])
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(whitelisted_user_params)
			flash[:success] = "User saved successfully!"
			redirect_to admin_user_path(@user.id)
		else
			render :new
		end
	end

	def destroy
		@user = User.find(params[:id])
		if @user.destroy
			flash[:success] = "User deleted successfully!"
			redirect_to admin_users_path
		else
			redirect_to session.delete(:return_to)
		end
	end

private 
	def whitelisted_user_params
		params.require(:user).permit(:first_name, :last_name, :email, :billing_id, :shipping_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include UsersHelper

	def new
		current_user
		@user = User.new
		@addresses = [Address.new, Address.new]
	end

	def create
		@user = User.new(whitelisted_user_params)
		if @user.save
			flash[:success] = "User created successfully. Please set default shipping and billing addresses!"
			sign_in(@user)
			redirect_to edit_user_path
		else
			flash.now[:error] = "Failed to create user"
			render :new
		end
	end

	def edit
		current_user
		@current_user.addresses.build
		@addresses = @current_user.addresses
	end

	def update
		current_user
		if @current_user.update(whitelisted_user_params)
			flash[:success] = "User updated successfully"
			set_user_addresses(params, @current_user)
			redirect_to root_path
		else
			flash[:error] = "User could not be updated"
			render :edit
		end
	end

	def destroy
		current_user
		if @current_user.destroy
			flash[:success] = "Successfully deleted user."
			sign_out
			redirect_to root_path
		else
			flash[:error] = "Aliens stopped us from deleting this user, HELP!"
			render :edit
		end
	end

private
	def whitelisted_user_params
		params.require(:user).
			permit(:first_name,
						 :last_name,
             :email,
             :addresses_attributes => [
             		:street_address,
             		:city_id, 
             		:state_id,
             		:zip_code, 
             		:id, 
             		:_destroy
             ],
             :credit_card_attributes => [
		           		:card_number,
		           		:exp_month,
		           		:exp_year
		         ]
			)
	end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper

	# TODO: Fix shipping/billing to first letter of string on User show page when
	# address not set.
	
	def user_shipping_address(user)
		if user.shipping_address
			[user.shipping_address.street_address, user.shipping_id]
		else
			"Shipping Not Set"
		end
	end

	def user_billing_address(user)
		if user.billing_address
			[user.billing_address.street_address, user.billing_id]
		else
			"Billing Not Set"
		end
	end

	def disable_address_field?
		action_name == "new" ? true : false
	end

end

app/helpers/users_helper.rb
module UsersHelper

	def is_default_shipping?(id)
		@current_user.shipping_id == id ? true : false
	end

	def is_default_billing?(id)
		@current_user.billing_id == id ? true : false
	end

	def set_user_addresses(params, user)
		
		if params[:default_billing]
			user.update(:billing_id => params[:default_billing])
		end

		if params[:default_shipping]
			user.update(:shipping_id => params[:default_shipping])
		end

	end
end

app/views/admin/users/_new_user_form.html.erb
<%= form_for [:admin, @user] do |f| %>
	
	<div class="form-group">
		<%= f.label :id, "ID" %>
		<%= f.text_field :id, class: "form-control", :disabled => true %>
	</div>
	
	<div class="form-group">
		<%= f.label :first_name, "First Name" %>
		<%= f.text_field :first_name, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :last_name, "Last Name" %>
		<%= f.text_field :last_name, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :email, "Email" %>
		<%= f.email_field :email, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :billing_id, "Billing Address" %>
		<%= f.collection_select(:billing_id, Address.all, :id, :street_address, {prompt: true}, {class: "form-control", disabled: disable_address_field? } ) %>
	</div>

	<div class="form-group">
		<%= f.label :shipping_id, "Shipping Address" %>
		<%= f.collection_select(:shipping_id, Address.all, :id, :street_address, {prompt: true}, {class: "form-control", disabled: disable_address_field? } ) %>
	</div>

	<%= f.submit :class => "btn btn-primary" %>

<% end %>

app/views/admin/users/edit.html.erb
<h2>Edit User <%= @user.first_name %> <%= @user.last_name %>:</h2>

<%= render partial: "admin/shared/errors", :locals => { :error_object => @user } %>

<%= render partial: "new_user_form", :locals => { :user => @user } %>

<%= link_to "Delete User", admin_user_path, :method => :delete, class: "btn btn-warning action-button" %>

app/views/admin/users/index.html.erb
<!-- Users Index Page -->
<h2>Users:</h2>
<%= link_to "Create New User", new_admin_user_path, class: "btn btn-primary action-button" %>
<table class="table table-striped">

	<thead class="all-bold">
		<tr>
			<td>ID</td>
			<td>First Name</td>
			<td>Last Name</td>
			<td>Email</td>
			<td>Addresses</td>
			<td>Orders</td>
			<td>Actions</td>
		</tr>
	</thead>
	
	<tbody>
		
		<% @users.each do |user| %>
	
			<tr>
				<td><%= user.id %></td>
				<td><%= user.first_name %></td>
				<td><%= user.last_name %></td>
				<td><%= user.email %></td>
				<td>
					<% if user.addresses %>
						<%= link_to "Addresses", admin_addresses_path(:search_user_id => user.id) %>
					<% end %>
				</td>
				<td><%= link_to "Orders", "#" %></td>
				<td>
					<%= link_to "Show", admin_user_path(user) %> | 
					<%= link_to "Edit", edit_admin_user_path(user) %> | 
					<%= link_to "Delete", admin_user_path(user), :method => :delete, :data => {:confirm=>'Are you sure?'} %>
				</td>
			</tr>

		<% end %>

	</tbody>
</table>

app/views/admin/users/new.html.erb
<h2>Create New User</h2>

<%= render partial: "admin/shared/errors", :locals => { :error_object => @user } %>

<%= render partial: "new_user_form", :locals => { :user => @user } %>

app/views/admin/users/show.html.erb
<!-- Users Index Page -->
<h2>User <%= @user.first_name %> <%= @user.last_name %>:</h2>
<table class="table table-striped">

	<thead class="all-bold">
		<tr>
			<td>ID</td>
			<td>First Name</td>
			<td>Last Name</td>
			<td>Email</td>
			<td>Orders</td>
			<td>Shipping Add.</td>
			<td>Billing Add.</td>
			<td>Credit Card #</td>
			<td>Actions</td>
		</tr>
	</thead>
	
	<tbody>
	
		<tr>
			<td><%= @user.id %></td>
			<td><%= @user.first_name %></td>
			<td><%= @user.last_name %></td>
			<td><%= @user.email %></td>
			<td><%= link_to "Orders", "#" %></td>
			<td><%= link_to user_shipping_address(@user)[0], admin_address_path(user_shipping_address(@user)[1]) %></td>
			<td><%= link_to user_billing_address(@user)[0], admin_address_path(user_billing_address(@user)[1]) %></td>
			<td><%= @user_credit_card.card_number if @user_credit_card %></td>
			<td> 
				<!-- has_cart? available in UserHelper --> 
				<% if has_cart?(@user) %>
					<%= link_to "Cart", edit_admin_user_path(@user) %> | 
				<% end %>			
				<%= link_to "Edit", edit_admin_user_path(@user) %> | 
				<%= link_to "Delete", admin_user_path(@user), :method => :delete, :data => {:confirm=>'Are you sure?'} %>
				<% if @user_credit_card %>
					| <%= link_to "Delete CC Info TODO", admin_credit_card_path(@user_credit_card), :method => :delete, :data => {:confirm=>'Are you sure?'} %>
				<% end %>
			</td>
		</tr>

	</tbody>
</table>

<h2>Order History:</h2>
<table class="table table-striped">

	<thead class="all-bold">
		<tr>
			<td>ID</td>
			<td>Checkout Date</td>
		</tr>
	</thead>
	
	<tbody>
	
		<% unless @orders.nil? %>
			<% @orders.each do |order| %>

				<tr>
					<td><%= order.id %></td>
					<td><%= order.checkout_date || "NULL" %></td>
					<td> 	
						<%= link_to "Show", admin_order_path(order.id) %> |	
						<%= link_to "Edit", edit_admin_order_path(order) %> | 
						<%= link_to "Delete", admin_order_path(order), :method => :delete, :data => {:confirm=>'Are you sure?'} %>
					</td>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>

<%= link_to "Add Address", "#", class: "btn btn-primary action-button" %>
<%= link_to "Create Order", "#", class: "btn btn-primary action-button" %>